# AI Prompts Configuration for Language Focus Learning Bot
# All prompts are in Russian for better context understanding

prompts:
  feedback_analysis:
    system_prompt: |
      Вы эксперт по языковым фокусам НЛП (фокусы языка) - техникам вербального рефрейминга.
      Фокусы языка направлены на работу с возражениями.
      Анализируйте ответы пользователей и предоставляйте конструктивную обратную связь на русском языке.
      
      Ваша задача:
      1. Определить, правильно ли применен языковой фокус
      2. Оценить качество ответа по шкале 0-100
      3. Дать полезную обратную связь
      4. Предложить улучшения при необходимости
      
      Будьте поддерживающими и конструктивными в своих оценках. 
      На высокую оценку более 80 оценивайте лишь очень качественные и точно соответсвующие ответы.
    
    user_prompt_template: |
      Проанализируйте использование языкового фокуса:
      
      Исходное утверждение: "{statement}"
      Целевой фокус: {trick_name} - {trick_definition}
      Ответ пользователя: "{user_response}"
      Примеры правильного использования: {examples}
      
      Оцените:
      1. Правильно ли пользователь применил фокус "{trick_name}"?
      2. Оцените качество ответа (0-100 баллов)
      3. Дайте конструктивную обратную связь на русском языке
      4. Предложите конкретные улучшения при необходимости
      
      Верните ответ строго в JSON формате:
      {{
          "is_correct": boolean,
          "score": number,
          "feedback": "string",
          "improvements": ["string"],
          "detected_trick": "string or null"
      }}

  trick_classification:
    system_prompt: |
      Вы эксперт по классификации языковых фокусов НЛП (фокусы языка).
      Определите, какой именно фокус был использован в ответе пользователя.
      
      Доступные фокусы:
      1. Намерение - высказывания о намерениях, желаниях, устремлениях
      2. Переопределение - замена критерия на синоним
      3. Последствия - обращение внимания к результатам действий
      4. Разделение - дробление на части и уточнение деталей
      5. Объединение - обобщение, укрупнение сказанного
      6. Аналогия - объяснение примером из других контекстов
      7. Модель мира - ссылка на авторитеты и другие мнения
      8. Стратегия реальности - вопросы о происхождении убеждения
      9. Иерархия критериев - переключение на более значимые ценности
      10. Изменение размеров фрейма - изменение временной/пространственной рамки
      11. Другой результат - рассмотрение побочных эффектов
      12. Противоположный пример - поиск исключений из правила
      13. Метафрейм - оценка самого убеждения
      14. Применение к себе - проверка применимости к самому человеку
    
    user_prompt_template: |
      Классифицируйте языковой фокус НЛП, использованный в этом ответе:
      
      Исходное утверждение: "{statement}"
      Ответ пользователя: "{user_response}"
      
      Доступные фокусы: {available_tricks}
      
      Верните ID фокуса и уровень уверенности (0-100) в JSON формате:
      {{
          "detected_trick_id": number,
          "confidence": number,
          "explanation": "string"
      }}
      Уровень уверенности должен соответсвовать тому удалось ли ответу пользователя обработать исходное утверждение, 
      возражение и насколько грамотно.

  encouragement:
    high_score: |
      🎉 Отлично! Вы правильно применили фокус "{trick_name}". 
      Ваш ответ показывает хорошее понимание техники.
      Балл: {score}/100
    
    medium_score: |
      👍 Хорошая попытка! Вы на правильном пути с фокусом "{trick_name}".
      Небольшие улучшения помогут сделать ответ еще лучше.
      Балл: {score}/100
    
    low_score: |
      💪 Здорово! Изучение фокусов языка требует практики.
      Давайте разберем, как лучше применить "{trick_name}".
      Балл: {score}/100

  session_summary:
    completion_template: |
      🎓 Сессия завершена!
      
      📊 Ваши результаты:
      • Изучено фокусов: {tricks_practiced}/14
      • Средний балл: {average_score}/100
      • Правильных ответов: {correct_answers}/{total_attempts}
      • Время сессии: {session_duration}
      
      🎯 Рекомендации для дальнейшего изучения:
      {recommendations}
      
      Продолжайте практиковаться! 💪

  progress_messages:
    mastery_achieved: |
      🏆 Поздравляем! Вы освоили фокус "{trick_name}"!
      Уровень мастерства: {mastery_level}%
      
      Теперь вы можете уверенно использовать эту технику в общении.
    
    progress_update: |
      📈 Прогресс по фокусу "{trick_name}": {mastery_level}%
      Попыток: {attempts} | Правильных: {correct}
      
      {encouragement_message}
    
    level_up: |
      ⭐ Новый уровень! Ваше мастерство в "{trick_name}" выросло до {mastery_level}%!
      
      Отличная работа! Продолжайте в том же духе.

  learning_tips:
    general_tips:
      - "Читайте ответ вслух - это поможет почувствовать естественность фразы"
      - "Представьте реальную ситуацию, где бы вы использовали этот фокус"
      - "Обращайте внимание на эмоциональную окраску ваших ответов"
      - "Практикуйтесь с разными типами утверждений для лучшего понимания"
      - "Изучайте примеры и адаптируйте их под свой стиль общения"
    
    trick_specific_tips:
      1: "Для фокуса 'Намерение': ищите скрытые желания и мотивы за словами"
      2: "Для фокуса 'Переопределение': подбирайте синонимы с другой эмоциональной окраской"
      3: "Для фокуса 'Последствия': думайте о долгосрочных результатах действий"
      4: "Для фокуса 'Разделение': разбивайте общие утверждения на конкретные части"
      5: "Для фокуса 'Объединение': ищите общие закономерности и тенденции"
      6: "Для фокуса 'Аналогия': используйте яркие и понятные сравнения"
      7: "Для фокуса 'Модель мира': ссылайтесь на авторитетные источники"
      8: "Для фокуса 'Стратегия реальности': задавайте вопросы об источниках информации"
      9: "Для фокуса 'Иерархия критериев': определяйте, что действительно важно"
      10: "Для фокуса 'Изменение размеров фрейма': меняйте временную перспективу"
      11: "Для фокуса 'Другой результат': ищите неожиданные положительные эффекты"
      12: "Для фокуса 'Противоположный пример': находите исключения из правил"
      13: "Для фокуса 'Метафрейм': оценивайте само убеждение как концепцию"
      14: "Для фокуса 'Применение к себе': проверяйте логику на собственном опыте"

  error_messages:
    ai_error: "Извините, произошла ошибка при анализе вашего ответа. Попробуйте еще раз."
    timeout_error: "Анализ занимает слишком много времени. Попробуйте сформулировать ответ проще."
    invalid_response: "Не удалось понять ваш ответ. Пожалуйста, попробуйте еще раз."
    session_expired: "Ваша сессия истекла. Начните новую сессию командой /learn"